/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.csp.frames;

import com.csp.dao.EmployeeDao;
import com.csp.daoimpl.EmployeeDaoImpl;
import com.csp.model.EmployeeBean;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class AddEmployee extends javax.swing.JFrame {

    /**
     * Creates new form AddEmployee
     */
    public AddEmployee() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addEmployeePanel = new javax.swing.JPanel();
        usernameField = new javax.swing.JTextField();
        outletLabel = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        salaryField = new javax.swing.JTextField();
        categoryLabel = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        sizeLabel = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        exit = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        addEmployeePanel.setBackground(new java.awt.Color(78, 139, 183));
        addEmployeePanel.setForeground(new java.awt.Color(32, 32, 32));
        addEmployeePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usernameField.setBackground(new java.awt.Color(78, 139, 183));
        usernameField.setForeground(new java.awt.Color(32, 32, 32));
        usernameField.setBorder(null);
        usernameField.setOpaque(false);
        usernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameFieldActionPerformed(evt);
            }
        });
        addEmployeePanel.add(usernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 290, -1));

        outletLabel.setBackground(new java.awt.Color(210, 236, 184));
        outletLabel.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        outletLabel.setForeground(new java.awt.Color(32, 32, 32));
        outletLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        outletLabel.setText("Username");
        addEmployeePanel.add(outletLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 70, -1));
        addEmployeePanel.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 290, 10));

        salaryField.setBackground(new java.awt.Color(78, 139, 183));
        salaryField.setForeground(new java.awt.Color(32, 32, 32));
        salaryField.setBorder(null);
        salaryField.setOpaque(false);
        addEmployeePanel.add(salaryField, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 290, -1));

        categoryLabel.setBackground(new java.awt.Color(210, 236, 184));
        categoryLabel.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        categoryLabel.setForeground(new java.awt.Color(32, 32, 32));
        categoryLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        categoryLabel.setText("Password");
        addEmployeePanel.add(categoryLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 70, -1));
        addEmployeePanel.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 290, 10));
        addEmployeePanel.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 290, 10));

        sizeLabel.setBackground(new java.awt.Color(210, 236, 184));
        sizeLabel.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        sizeLabel.setForeground(new java.awt.Color(32, 32, 32));
        sizeLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        sizeLabel.setText("Salary");
        addEmployeePanel.add(sizeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 80, 20));

        addButton.setBackground(java.awt.Color.white);
        addButton.setText("Add");
        addButton.setFocusPainted(false);
        addButton.setSelected(true);
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        addEmployeePanel.add(addButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 470, 210, 30));

        exit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        exit.setForeground(new java.awt.Color(232, 17, 35));
        exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit.setText("X");
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        addEmployeePanel.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 20, -1));

        passwordField.setBackground(new java.awt.Color(78, 139, 183));
        passwordField.setForeground(new java.awt.Color(32, 32, 32));
        passwordField.setBorder(null);
        addEmployeePanel.add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 290, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addEmployeePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addEmployeePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void usernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameFieldActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        EmployeeBean eb = new EmployeeBean();
        EmployeeDao ed = new EmployeeDaoImpl();
        
        String password = new String(passwordField.getPassword());
        if(!(usernameField.getText().equals("") || password.equals("") || salaryField.getText().equals(""))){
            eb.setUsername(usernameField.getText());
            eb.setSalary(Integer.parseInt(salaryField.getText()));
            eb.setPassword(password);
            eb.setType("employee");
            
            if(ed.addEmployee(eb)>0){
                JOptionPane.showMessageDialog(this,"Employee Added!");
                usernameField.setText("");
                passwordField.setText("");
                salaryField.setText("");
            }
            else
            JOptionPane.showMessageDialog(this, "Employee Could Not Be Added!");
        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        this.dispose();
    }//GEN-LAST:event_exitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JPanel addEmployeePanel;
    private javax.swing.JLabel categoryLabel;
    private javax.swing.JLabel exit;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel outletLabel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTextField salaryField;
    private javax.swing.JLabel sizeLabel;
    private javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables
}
