/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.csp.frames;

import com.csp.dao.PurchaseLogDAO;
import com.csp.daoimpl.PurchaseLogDAOImpl;
import com.csp.model.PurchaseLogBean;
import java.util.Stack;

/**
 *
 * @author Lenovo
 */
public class ShowLogs extends javax.swing.JFrame {

    private int count=0;
    PurchaseLogDAO logsDAO = new PurchaseLogDAOImpl();
    Stack<PurchaseLogBean> logs = logsDAO.getAllLogs();
    
    PurchaseLogBean log;
    /**
     * Creates new form ShowLogs
     */
    public ShowLogs() {
        initComponents();
        showLogs();
    }
    
    
    private void showLogs() {
        
        for(int i=count;i<=count;i++)
        {          
           log = logs.pop();
           idField.setText(""+log.getLogID());
           userIDField.setText(""+log.getEmpID());
           itemsSoldField.setText(log.getItemsSold());
           dateSoldField.setText(log.getDateSold());
           cashRecievedField.setText(""+log.getCashRecieved());
           cashBackField.setText(""+log.getCashBack());
           if(logs.isEmpty()){
               logs = logsDAO.getAllLogs();
               count=0;
           }
        }  
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        updateEmployeePanel = new javax.swing.JPanel();
        itemsSoldField = new javax.swing.JTextField();
        outletLabel = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        cashRecievedField = new javax.swing.JTextField();
        categoryLabel = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        sizeLabel = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();
        idField = new javax.swing.JLabel();
        nextButton = new javax.swing.JButton();
        categoryLabel1 = new javax.swing.JLabel();
        cashBackField = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        sizeLabel1 = new javax.swing.JLabel();
        userIDField = new javax.swing.JTextField();
        dateSoldField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        updateEmployeePanel.setBackground(new java.awt.Color(78, 139, 183));
        updateEmployeePanel.setForeground(new java.awt.Color(32, 32, 32));
        updateEmployeePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        itemsSoldField.setEditable(false);
        itemsSoldField.setBackground(new java.awt.Color(78, 139, 183));
        itemsSoldField.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        itemsSoldField.setForeground(new java.awt.Color(32, 32, 32));
        itemsSoldField.setBorder(null);
        itemsSoldField.setOpaque(false);
        itemsSoldField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemsSoldFieldActionPerformed(evt);
            }
        });
        updateEmployeePanel.add(itemsSoldField, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 290, -1));

        outletLabel.setBackground(new java.awt.Color(210, 236, 184));
        outletLabel.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        outletLabel.setForeground(new java.awt.Color(32, 32, 32));
        outletLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        outletLabel.setText("User ID:");
        updateEmployeePanel.add(outletLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 70, -1));
        updateEmployeePanel.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 290, 10));

        cashRecievedField.setEditable(false);
        cashRecievedField.setBackground(new java.awt.Color(78, 139, 183));
        cashRecievedField.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        cashRecievedField.setForeground(new java.awt.Color(32, 32, 32));
        cashRecievedField.setBorder(null);
        cashRecievedField.setOpaque(false);
        updateEmployeePanel.add(cashRecievedField, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 290, -1));

        categoryLabel.setBackground(new java.awt.Color(210, 236, 184));
        categoryLabel.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        categoryLabel.setForeground(new java.awt.Color(32, 32, 32));
        categoryLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        categoryLabel.setText("Items Sold:");
        updateEmployeePanel.add(categoryLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 90, -1));
        updateEmployeePanel.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 290, 10));
        updateEmployeePanel.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 290, 10));

        sizeLabel.setBackground(new java.awt.Color(210, 236, 184));
        sizeLabel.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        sizeLabel.setForeground(new java.awt.Color(32, 32, 32));
        sizeLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        sizeLabel.setText("Date Sold:");
        updateEmployeePanel.add(sizeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 80, 20));

        exit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        exit.setForeground(new java.awt.Color(232, 17, 35));
        exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit.setText("X");
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        updateEmployeePanel.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 30, 30));

        idLabel.setBackground(new java.awt.Color(78, 139, 183));
        idLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        idLabel.setForeground(new java.awt.Color(32, 32, 32));
        idLabel.setText("ID :");
        updateEmployeePanel.add(idLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 30, 20));

        idField.setBackground(new java.awt.Color(78, 139, 183));
        idField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        idField.setForeground(new java.awt.Color(32, 32, 32));
        idField.setText("0");
        updateEmployeePanel.add(idField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 30, 20));

        nextButton.setText("Next");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });
        updateEmployeePanel.add(nextButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 470, 70, 30));

        categoryLabel1.setBackground(new java.awt.Color(210, 236, 184));
        categoryLabel1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        categoryLabel1.setForeground(new java.awt.Color(32, 32, 32));
        categoryLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        categoryLabel1.setText("Cash Recieved:");
        updateEmployeePanel.add(categoryLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 100, -1));

        cashBackField.setEditable(false);
        cashBackField.setBackground(new java.awt.Color(78, 139, 183));
        cashBackField.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        cashBackField.setForeground(new java.awt.Color(32, 32, 32));
        cashBackField.setBorder(null);
        cashBackField.setOpaque(false);
        updateEmployeePanel.add(cashBackField, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 290, -1));
        updateEmployeePanel.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 290, 10));
        updateEmployeePanel.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 290, 10));

        sizeLabel1.setBackground(new java.awt.Color(210, 236, 184));
        sizeLabel1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        sizeLabel1.setForeground(new java.awt.Color(32, 32, 32));
        sizeLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        sizeLabel1.setText("Cash Back:");
        updateEmployeePanel.add(sizeLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 80, 20));

        userIDField.setEditable(false);
        userIDField.setBackground(new java.awt.Color(78, 139, 183));
        userIDField.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        userIDField.setForeground(new java.awt.Color(32, 32, 32));
        userIDField.setBorder(null);
        userIDField.setOpaque(false);
        userIDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userIDFieldActionPerformed(evt);
            }
        });
        updateEmployeePanel.add(userIDField, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 290, -1));

        dateSoldField.setEditable(false);
        dateSoldField.setBackground(new java.awt.Color(78, 139, 183));
        dateSoldField.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        dateSoldField.setForeground(new java.awt.Color(32, 32, 32));
        dateSoldField.setBorder(null);
        dateSoldField.setOpaque(false);
        updateEmployeePanel.add(dateSoldField, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 290, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(updateEmployeePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(updateEmployeePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void itemsSoldFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemsSoldFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemsSoldFieldActionPerformed

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        this.dispose();
    }//GEN-LAST:event_exitMouseClicked

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        count++;
        showLogs();
    }//GEN-LAST:event_nextButtonActionPerformed

    private void userIDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userIDFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userIDFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowLogs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowLogs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowLogs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowLogs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShowLogs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cashBackField;
    private javax.swing.JTextField cashRecievedField;
    private javax.swing.JLabel categoryLabel;
    private javax.swing.JLabel categoryLabel1;
    private javax.swing.JTextField dateSoldField;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel idField;
    private javax.swing.JLabel idLabel;
    private javax.swing.JTextField itemsSoldField;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JButton nextButton;
    private javax.swing.JLabel outletLabel;
    private javax.swing.JLabel sizeLabel;
    private javax.swing.JLabel sizeLabel1;
    private javax.swing.JPanel updateEmployeePanel;
    private javax.swing.JTextField userIDField;
    // End of variables declaration//GEN-END:variables

}
